[package]
edition = "2021"
name = "lowestbins"
version = "1.3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["simd"]
simd = ["simd-json"]
[profile.release]
lto = true
strip = true

[build-dependencies]
colored = "2.0"

[dependencies]
anyhow = "1.0"
dashmap = { version = "5.4", features = [
    "serde",
] }
base64 = { version = "0.13" }
futures = { version = "0.3", features = [
    "async-await",
] }
hematite-nbt = "0.5.2"
hyper = { version = "0.14", features = [
    "server",
    "runtime",
    "stream",
    "http1",
    "http2",
] }
lazy_static = "1.4"
serde = { version = "1", features = [
    "derive",
] }
serde_json = "1.0"
simd-json = { version = "0.6", optional = true }
surf = { version = "2.3", default-features = false, features = [
    "curl-client",
    "rustls_crate",
] }
tokio = { version = "1", features = [
    "rt",
    "rt-multi-thread",
    "macros",
    "tracing",
] }
ctrlc = "3.2"
tracing = { version = "0", features = [
    "log",
    "async-await",
] }
rustls = "0"
tracing-subscriber = "0.3.15"
