[package]
name = "lowestbins"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.130"
serde_json = "1.0"
hyper = { version = "0.14", features = ["full"] }
pretty_env_logger = "0.4"
tokio-util = "0.6.8"
serde_derive = "1.0.130"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
