[package]
edition = "2021"
name = "lowestbins"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
base64 = {version = "0.13.0"}
futures = {version = "0.3.17", features = ["async-await"]}
hematite-nbt = {version = "0.5.2"}
hyper = {version = "0.14", features = ["server", "runtime", "stream", "http1", "http2"]}
lazy_static = "1.4.0"
serde = {version = "1", features = ["derive"]}
serde_json = "1.0"
surf = {version = "2.3.2", features = ["curl-client"]}
tokio = {version = "1", features = ["rt", "rt-multi-thread", "macros", "time"]}
