[package]
edition = "2021"
name = "lowestbins"
version = "1.3.2"
authors = ["Tricked-dev <tricked@tricked.pro>"]
description = "Lowestbins made in rust for maximum efficiency"
repository = "https://github.com/tricked-dev/lowestbins"
documentation = "https://docs.rs/lowestbins"
readme = "README.md"
license = "Apache-2.0"
homepage = "https://lb.tricked.pro"
categories = ["command-line-utilities"]
exclude = [".vscode/settings.json", "makefile"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["simd"]
simd = ["simd-json"]
local = []

[profile.release]
lto = true
strip = true
codegen-units = 1
incremental = true
opt-level = 'z'

[profile.release.package."*"]
opt-level = 3

[build-dependencies]
colored = "2.0"

[dependencies]
anyhow = "1.0"
dashmap = { version = "5.4", features = ["serde"] }
base64 = { version = "0.13" }
futures = { version = "0.3", features = ["async-await"] }
hematite-nbt = "0.5.2"
hyper = { version = "0.14", features = [
    "server",
    "runtime",
    "stream",
    "http1",
    "http2",
] }
lazy_static = "1.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
simd-json = { version = "0.6", optional = true }
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
ctrlc = "3.2"
tracing = { version = "0", features = ["log", "async-await"] }
tracing-subscriber = "0.3.15"
isahc = { version = "1.7.2", features = ["serde", "serde_json"] }
flate2 = "1"

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }

[[bench]]
name = "bench_main"
harness = false

[package.metadata.docs.rs]
no-default-features = true
