name: Build and upload artifacts.

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: ""

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cargo Caching
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --release --no-default-features
      - run: cp target/release/lowestbins .
      - run: rm -rf target/
      - name: Build and push
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          registry: ghcr.io
          image: "lowestbins"
          dockerfile: Dockerfile.prebuild
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - uses: actions/upload-artifact@v2
        with:
          name: lowestbins
          path: target/release/lowestbins
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
